# Spletne strani
endpoints:
  
  - name: Urnik
    url: https://urnik.fri.uni-lj.si
    method: GET
    timeout: 1s
    expectation:
      - type: HTTP_STATUS
        status_range: 200-205
      - type: LATENCY
        threshold: 0.3
    allowed_fails: 1
    component_id: 1
    metric_id: 1
    action:
      - UPDATE_STATUS
      - PUSH_METRICS
    public_incidents: true
    latency_unit: ms
    frequency: 60

  - name: STUDIS
    url: https://studij.fri.uni-lj.si
    method: GET
    timeout: 1s
    expectation:
      - type: HTTP_STATUS
        status_range: 200-205
      - type: LATENCY
        threshold: 0.3
    allowed_fails: 1
    component_id: 1
    metric_id: 1
    action:
      - UPDATE_STATUS
      - PUSH_METRICS
    public_incidents: true
    latency_unit: ms
    frequency: 60

  - name: STUDIS
    url: https://studij.fri.uni-lj.si
    method: GET
    timeout: 1s
    expectation:
      - type: HTTP_STATUS
        status_range: 200-205
      - type: LATENCY
        threshold: 0.3
    allowed_fails: 1
    component_id: 1
    metric_id: 1
    action:
      - UPDATE_STATUS
      - PUSH_METRICS
    public_incidents: true
    latency_unit: ms
    frequency: 60

cachet:
  api_url:
    - type: ENVIRONMENT_VARIABLE
      value: CACHET_API
  token:
    - type: ENVIRONMENT_VARIABLE
      value: CACHET_TOKEN
  messages:
    incident_outage: "{name} is DOWN"
    incident_operational: "{name} is UP"